### ISSUE TITLE
Many  "Not properly disposed SWT resource" in error log

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-mylyn/org.eclipse.mylyn#167]
When navigating around Mylyn I see the following error repeatedly with the key item on the stack seeming to be `org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.computeIconImage(DiscoveryViewer.java:549)`

<details>
<summary>full log</summary>

```

!ENTRY org.eclipse.ui.ide 4 4 2023-05-25 18:55:38.615
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:655)
	at org.eclipse.jface.resource.URLImageDescriptor.createImage(URLImageDescriptor.java:311)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:290)
	at org.eclipse.jface.resource.ImageDescriptor.createImage(ImageDescriptor.java:268)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.computeIconImage(DiscoveryViewer.java:549)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.access$3(DiscoveryViewer.java:525)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer$ConnectorDescriptorItemUi.<init>(DiscoveryViewer.java:221)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.createDiscoveryContents(DiscoveryViewer.java:990)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.createBodyContents(DiscoveryViewer.java:611)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.discoveryUpdated(DiscoveryViewer.java:1057)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.DiscoveryViewer.updateDiscovery(DiscoveryViewer.java:1538)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.ConnectorDiscoveryWizardMainPage.maybeUpdateDiscovery(ConnectorDiscoveryWizardMainPage.java:82)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.ConnectorDiscoveryWizardMainPage.access$2(ConnectorDiscoveryWizardMainPage.java:80)
	at org.eclipse.mylyn.internal.discovery.ui.wizards.ConnectorDiscoveryWizardMainPage$2.run(ConnectorDiscoveryWizardMainPage.java:92)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.mylyn.internal.tasks.ui.commands.ShowTasksConnectorDiscoveryWizardCommandHandler.execute(ShowTasksConnectorDiscoveryWizardCommandHandler.java:71)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:309)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:243)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:366)
	at org.eclipse.mylyn.internal.tasks.ui.wizards.SelectRepositoryConnectorPage$3.widgetSelected(SelectRepositoryConnectorPage.java:152)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.mylyn.internal.tasks.ui.actions.AddRepositoryAction.showWizard(AddRepositoryAction.java:90)
	at org.eclipse.mylyn.internal.tasks.ui.actions.AddRepositoryAction.showWizard(AddRepositoryAction.java:80)
	at org.eclipse.mylyn.internal.tasks.ui.actions.AddRepositoryAction.run(AddRepositoryAction.java:76)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:453)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

</details>

**Comment by wimjongman** [comment]
Yes that class has a logic flaw. Probably caused by #166

**Comment by jonahgraham** [comment]
Thanks for fixing so many of these errors. I have identified one additional one which I raised in #186
