### ISSUE TITLE
Support Dark Theme

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#44]
Mylyn doesn't play well with Dark Theme. 
It uses hard coded colors that are close to impossible to read in Dark Mode.

An example is TaskScalingHyperlink which uses CommonColors.HYPERLINK_WIDGET

`public class CommonColors {

        public static final Color HYPERLINK_WIDGET = new Color(Display.getDefault(), 12, 81, 172);

        public static final Color TEXT_QUOTED = new Color(Display.getDefault(), 38, 86, 145);
`

**Comment by BeckerFrank** [comment]
What is with the other Color Definitions?
We also have Class org.eclipse.mylyn.internal.context.ui.ColorMap.

**Comment by gnl42** [comment]
And org.eclipse.mylyn.internal.commons.ui.E4ThemeColor which tries to parse `#org-eclipse-ui-workbench-DARK_BACKGROUND` as a RGB value:

`java.lang.NumberFormatException: For input string: "or" under radix 16
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at org.eclipse.mylyn.internal.commons.ui.E4ThemeColor.getRGBFromCssString(E4ThemeColor.java:57)
	at org.eclipse.mylyn.commons.ui.GradientColors.getRGBFromTheme(GradientColors.java:211)`

**Comment by gnl42** [comment]
I could use suggestions/pointers on how to go about doing this.

I have no experience with SWT UI programming. Trying to make sense of the various articles on Eclipse themes but unsure how to actually apply them..

Are custom colours really needed? Or are Eclipse defaults good enough?

**Comment by wimjongman** [comment]
> Are custom colours really needed? Or are Eclipse defaults good enough?

When possible, Eclipse defaults would be the way to go.

https://www.vogella.com/tutorials/Eclipse4CSS/article.html contains many clues, but you probably already found it.

Theming is based on CSS, and when the plugin spy is installed, you can use CTRL+ALT+SHIFT+F6 to see how the component is styled.

Please ask specific questions and I will help.

**Comment by gruscoe-papajohns** [comment]
I am also facing this issue - and with the very latest release - Do we have any css info that can be manually added to 

`plugins/org.eclipse.ui.themes_1.2.2400.v20240213-1133/css/e4-dark_linux.css`

to specify font colors for mylyn?

**Comment by BeckerFrank** [comment]
@gnl42: We have deprecated CommonColors, can we close this issue or do you know another place with hard coded colors?

**Comment by gnl42** [comment]
There is org.eclipse.mylyn.internal.context.ui.ColorMap as well.

**Comment by gnl42** [comment]
Also TaskEditorFindSupport

**Comment by mjmeijer** [comment]
There was also a hard coded font and highlight color in the Task Context Decorator that caused problems since navigator can be set with font prefs as well. Old bug already in bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=321336

**Comment by gnl42** [comment]
!*$&^*&(*&  After years of cursing the Package Explorer color scheme in the Eclipse Dark Theme, I've just realized that it is due to Mylyn color choices when a Task is active:
<img width="679" height="550" alt="Image" src="https://github.com/user-attachments/assets/2d63c24d-047f-4e76-8154-a7439eaf87f9" />

vs not activated:
<img width="676" height="589" alt="Image" src="https://github.com/user-attachments/assets/355ec3ca-c207-42bf-b8d7-a7d6a5a52160" />

**Comment by vogella** [comment]
@gnl42 can you point me to the problems with theming?

**Comment by gnl42** [comment]
> [@gnl42](https://github.com/gnl42) can you point me to the problems with theming?

Hi @vogella,
   there are a few places that should be using themes rather than code:

- ColorMap: I tried to make it more usable with #1020, my crude attempt to make the harcoded  colors more usable with dark theme, but someone with a better color sense should really take a look at the values
- GradientDrawer,GradientColors should be using css
- #1202/#1203 was another crude attempt to add dark theme to wikitext, The colors need checking and I when I tried to use plugin.xml for dark theme it appeared to impact the "Package Editor" mylyn colors. I also couldn't make HtmlTextPresentationParser retrieve the current css at runtime from plugin.xml
- CommonFonts
- Don't know if 'SWT\.,*COLOR.*' uses needs addressing?

Those are the obvious ones that I could find. Hope it helps

Thanks
   George

**Comment by vogella** [comment]
> > [@gnl42](https://github.com/gnl42) can you point me to the problems with theming?
> 
> Hi [@vogella](https://github.com/vogella), there are a few places that should be using themes rather than code:
> 
> * ColorMap: I tried to make it more usable with [Quick hack for better colors with Dark Theme #44 #1020](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/1020), my crude attempt to make the harcoded  colors more usable with dark theme, but someone with a better color sense should really take a look at the values
> * GradientDrawer,GradientColors should be using css
> * [Add dark theme css to wikitext #1202](https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/1202)/[Add a dark theme css to wikitext #1202 #1203](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/1203) was another crude attempt to add dark theme to wikitext, The colors need checking and I when I tried to use plugin.xml for dark theme it appeared to impact the "Package Editor" mylyn colors. I also couldn't make HtmlTextPresentationParser retrieve the current css at runtime from plugin.xml
> * CommonFonts
> * Don't know if 'SWT.,_COLOR._' uses needs addressing?
> 
> Those are the obvious ones that I could find. Hope it helps
> 
> Thanks George

Thanks, George, that helps. I have a look.

**Comment by vogella** [comment]
https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/1257

**Comment by vogella** [comment]
I believe gradients do not look good these days, it was a good UI pattern in the Win XP area. https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/1259

**Comment by gnl42** [comment]
I vote for dropping gradients then.
