### ISSUE TITLE
An internal error occurred during: "Task List Indexer".

### ISSUE THREAD

**Issue by mjmeijer** [eclipse-mylyn/org.eclipse.mylyn#464]
Constant errors in Task List Indexer:

An internal error occurred during: "Task List Indexer".
Could not load codec 'Lucene95'. Did you forget to add lucene-backward-codecs.jar?

-- Error Details --
Date: Mon Mar 04 12:42:25 CET 2024
Message: An internal error occurred during: "Task List Indexer".
Severity: Error
Product: Eclipse IDE 4.30.0.20231201-1200 (org.eclipse.epp.package.rcp.product)
Plugin: org.eclipse.core.jobs
Session Data:
eclipse.buildId=4.30.0.20231201-1200
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_NL
Framework arguments:  -product org.eclipse.epp.package.rcp.product -keyring /Users//.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.rcp.product -keyring /Users//.eclipse_keyring

Exception Stack Trace:
java.lang.IllegalArgumentException: Could not load codec 'Lucene95'. Did you forget to add lucene-backward-codecs.jar?
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:520)
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:409)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:368)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:304)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:546)
	at org.apache.lucene.index.SegmentInfos$1.doBody(SegmentInfos.java:543)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:820)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:770)
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:548)
	at org.apache.lucene.index.SegmentInfos.readLatestCommit(SegmentInfos.java:532)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1011)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.createIndexWriter(TaskListIndex.java:1295)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.rebuildIndexCompletely(TaskListIndex.java:1241)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.maintainIndex(TaskListIndex.java:1109)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex$MaintainIndexJob.run(TaskListIndex.java:186)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (680b1072). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="/Users/maarten/Workspaces/workspace-eulumdattools/.metadata/.mylyn/.taskListIndex/segments_1z")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501)
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:375)
		... 13 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene95' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene99]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:118)
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:516)
	... 15 more

**Comment by ruspl-afed** [comment]
> Did you forget to add lucene-backward-codecs.jar?

Yes, it seems we did.

Does this make task list not functional? I hope it does not.
I don't want to change dependencies in a day before release, it is too risky for the rest of functionality.
We can consider having service release to fix this issue or just schedule it for 4.3.0

WDYT @mjmeijer ?

**Comment by mjmeijer** [comment]
It does not seem to process batch changes made in bugzilla web interface. So I would say: makes unusable.

**Comment by mjmeijer** [comment]
Removing `.metadata/.mylyn/.taskListIndex` resolves the issue. So why this error message?

**Comment by ruspl-afed** [comment]
Do you mean that adding codecs was not helpful?

**Comment by mjmeijer** [comment]
Or maybe I needed to do both, we'll never know.
