### ISSUE TITLE
Hudson connector needs JAXB-API with Java 11+

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#55]
Finally did some more exploring of the Hudson connector:

`
!ENTRY org.eclipse.mylyn.builds.ui 4 0 2023-02-18 01:36:33.085
!MESSAGE Server validation failed: Unexpected error: Implementation of JAXB-API has not been found on module path or classpath.
!STACK 1
org.eclipse.core.runtime.CoreException: Unexpected error: Implementation of JAXB-API has not been found on module path or classpath.
	at org.eclipse.mylyn.internal.hudson.core.HudsonCorePlugin.toCoreException(HudsonCorePlugin.java:62)
	at org.eclipse.mylyn.internal.hudson.core.HudsonServerBehaviour.refreshConfiguration(HudsonServerBehaviour.java:798)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation$1.run(RefreshConfigurationOperation.java:76)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation$1.run(RefreshConfigurationOperation.java:1)
	at org.eclipse.mylyn.builds.internal.core.util.BuildRunner.run(BuildRunner.java:73)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation.doRefresh(RefreshConfigurationOperation.java:73)
	at org.eclipse.mylyn.builds.ui.spi.BuildServerPart$Validator.run(BuildServerPart.java:140)
	at org.eclipse.mylyn.commons.repositories.ui.RepositoryLocationPart$2.run(RepositoryLocationPart.java:559)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.mylyn.internal.hudson.core.client.HudsonException: Implementation of JAXB-API has not been found on module path or classpath.
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.run(HudsonOperation.java:171)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.getJobsFromFolder(RestfulHudsonClient.java:340)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.getJobs(RestfulHudsonClient.java:267)
	at org.eclipse.mylyn.internal.hudson.core.HudsonServerBehaviour.refreshConfiguration(HudsonServerBehaviour.java:796)
	... 7 more
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.unmarshal(RestfulHudsonClient.java:455)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.doProcess(RestfulHudsonClient.java:318)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.doProcess(RestfulHudsonClient.java:1)
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.processAndRelease(HudsonOperation.java:221)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.execute(RestfulHudsonClient.java:309)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.execute(RestfulHudsonClient.java:1)
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.run(HudsonOperation.java:167)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:146)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
	... 20 more
!SUBENTRY 1 org.eclipse.mylyn.hudson.core 4 0 2023-02-18 01:36:33.085
!MESSAGE Unexpected error: Implementation of JAXB-API has not been found on module path or classpath.
!STACK 0
org.eclipse.mylyn.internal.hudson.core.client.HudsonException: Implementation of JAXB-API has not been found on module path or classpath.
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.run(HudsonOperation.java:171)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.getJobsFromFolder(RestfulHudsonClient.java:340)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.getJobs(RestfulHudsonClient.java:267)
	at org.eclipse.mylyn.internal.hudson.core.HudsonServerBehaviour.refreshConfiguration(HudsonServerBehaviour.java:796)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation$1.run(RefreshConfigurationOperation.java:76)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation$1.run(RefreshConfigurationOperation.java:1)
	at org.eclipse.mylyn.builds.internal.core.util.BuildRunner.run(BuildRunner.java:73)
	at org.eclipse.mylyn.builds.internal.core.operations.RefreshConfigurationOperation.doRefresh(RefreshConfigurationOperation.java:73)
	at org.eclipse.mylyn.builds.ui.spi.BuildServerPart$Validator.run(BuildServerPart.java:140)
	at org.eclipse.mylyn.commons.repositories.ui.RepositoryLocationPart$2.run(RepositoryLocationPart.java:559)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:375)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient.unmarshal(RestfulHudsonClient.java:455)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.doProcess(RestfulHudsonClient.java:318)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.doProcess(RestfulHudsonClient.java:1)
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.processAndRelease(HudsonOperation.java:221)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.execute(RestfulHudsonClient.java:309)
	at org.eclipse.mylyn.internal.hudson.core.client.RestfulHudsonClient$5.execute(RestfulHudsonClient.java:1)
	at org.eclipse.mylyn.internal.hudson.core.client.HudsonOperation.run(HudsonOperation.java:167)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:146)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230)
	... 20 more
`

**Comment by ruspl-afed** [comment]
@gnl42 do we have this problem in master?

**Comment by gnl42** [comment]
Yes, when you use Java 11 or above

**Comment by gnl42** [comment]
Sigh, started working on #63 and ran into complaint about unsolvable reference to jakarta.activation-api 1.2.2.

No idea where this came from. Upgrade to 2023-03, a new branch from main, something missed in the initial merge, ???
