### ISSUE TITLE
Automatic Eclipse updates keeps breaking Eclipse

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#574]
I've had a couple of times now where the automatic Eclipse update when starting has led to a broken Eclipse installation and I've had to re-do the Oomph setup.

After this mornings launch/update I now get:
```
!ENTRY org.eclipse.e4.ui.workbench.swt 4 2 2024-07-12 10:18:30.094
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench.swt".
!STACK 0
java.lang.NoSuchFieldError: Class org.eclipse.swt.graphics.Image does not have member field 'int currentDeviceZoom'
        at org.eclipse.swt.graphics.Image._createDisabled(Image.java:2528)
```

I can understand the need to keep Eclipse current for the next release but not at the expense of having to recreate one's environment and possible loose work not yet pushed to GutHub

**Comment by merks** [comment]
Did you do the update via Oomph setup tasks or via check for updates?  Can you share more of the stack trace so we can see what is accessing (an os-specific field) that doesn’t exist?

**Comment by merks** [comment]
I started my mylyn setup IDE and it came up with this:

![image](https://github.com/user-attachments/assets/9b63ca7e-852a-4c4c-a600-6663a3b945fc)

So I let it install those updates and now it's using 2024-09 M1:

![image](https://github.com/user-attachments/assets/326de4b5-1898-487c-971f-48fcbe7c1c89)

I don't see any problems...

Note that the update done by Oomph's p2 task is significantly different from that done by Check for Update (automatic or manual)  where the former does a full resolve from scratch and tends up update more things more deeply than does the latter...

**Comment by gnl42** [comment]
> Did you do the update via Oomph setup tasks or via check for updates? Can you share more of the stack trace so we can see what is accessing (an os-specific field) that doesn’t exist?

```
java.lang.NoSuchFieldError: Class org.eclipse.swt.graphics.Image does not have member field 'int currentDeviceZoom'
        at org.eclipse.swt.graphics.Image._createDisabled(Image.java:2528)
        at org.eclipse.swt.graphics.Image.<init>(Image.java:254)
        at org.eclipse.jface.resource.DerivedImageDescriptor.internalCreateImage(DerivedImageDescriptor.java:83)
        at org.eclipse.jface.resource.DerivedImageDescriptor.createResource(DerivedImageDescriptor.java:51)
        at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
        at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
        at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:88)
        at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:71)
        at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
        at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
        at org.eclipse.jface.action.ActionContributionItem.updateImages(ActionContributionItem.java:1017)
        at org.eclipse.jface.action.ActionContributionItem.updateToolItem(ActionContributionItem.java:777)
        at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:740)
        at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:714)
        at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:345)
        at org.eclipse.ui.internal.CoolBarToTrimManager.update(CoolBarToTrimManager.java:596)
        at org.eclipse.ui.internal.WorkbenchWindow.updateActionBars(WorkbenchWindow.java:2481)
        at org.eclipse.ui.internal.WWinActionBars.updateActionBars(WWinActionBars.java:123)
        at org.eclipse.ui.SubActionBars.updateActionBars(SubActionBars.java:602)
        at org.eclipse.ui.internal.e4.compatibility.ActionBars.updateActionBars(ActionBars.java:88)
        at org.eclipse.ui.internal.e4.compatibility.CompatibilityView$1.compute(CompatibilityView.java:203)
        at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.postProcess(ToolBarManagerRenderer.java:961)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
 ```

**Comment by gnl42** [comment]
@merks It was whatever task that runs during startup, same as what you saw

**Comment by merks** [comment]
On which OS are you?  I can't find that method in any of these:

- https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/cocoa/org/eclipse/swt/graphics/Image.java
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/graphics/Image.java
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Image.java

Maybe if you create an issue here someone will recognize the problem:

https://github.com/eclipse-platform/eclipse.platform.swt/issues

**Comment by gnl42** [comment]
Windows 11

**Comment by gnl42** [comment]
For some reason swt.win32_x86_64 didn't update from 20240624 to 20240704.

A fresh install fixed the issue
