### ISSUE TITLE
Could not load codec 'Lucene99' (again)

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#639]
Suddenly seeing this one again (#492).  Cleared up after I restart Eclipse
It's happened twice to me so far (different workspaces):

`java.lang.IllegalArgumentException: Could not load codec 'Lucene99'. Did you forget to add lucene-backward-codecs.jar?
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:521)
	at org.apache.lucene.index.SegmentInfos.parseSegmentInfos(SegmentInfos.java:410)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:369)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:305)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:88)
	at org.apache.lucene.index.StandardDirectoryReader$1.doBody(StandardDirectoryReader.java:77)
	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:821)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:109)
	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:67)
	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:60)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.getIndexReader(TaskListIndex.java:787)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.matches(TaskListIndex.java:583)
	at org.eclipse.mylyn.internal.tasks.index.ui.IndexedSubstringPatternFilter.isLeafMatch(IndexedSubstringPatternFilter.java:48)
	at org.eclipse.ui.dialogs.PatternFilter.isElementVisible(PatternFilter.java:230)
	at org.eclipse.ui.dialogs.PatternFilter.computeAnyVisible(PatternFilter.java:131)
	at org.eclipse.ui.dialogs.PatternFilter.isAnyVisible(PatternFilter.java:114)
	at org.eclipse.ui.dialogs.PatternFilter.isParentMatch(PatternFilter.java:250)
	at org.eclipse.ui.dialogs.PatternFilter.isElementVisible(PatternFilter.java:230)
	at org.eclipse.ui.dialogs.PatternFilter.select(PatternFilter.java:138)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:62)
	at org.eclipse.ui.dialogs.PatternFilter.filter(PatternFilter.java:85)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:855)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1025)
	at org.eclipse.jface.viewers.ColumnViewer.getSortedChildren(ColumnViewer.java:821)
	at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:690)
	at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2896)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:2031)
	at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:2004)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1961)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$3(StructuredViewer.java:1486)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1392)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:367)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1353)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1486)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:533)
	at org.eclipse.ui.dialogs.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:1008)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1447)
	at org.eclipse.ui.dialogs.FilteredTree$NotifyingTreeViewer.refresh(FilteredTree.java:996)
	at org.eclipse.ui.dialogs.FilteredTree$1.runInUIThread(FilteredTree.java:516)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4141)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3757)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:663)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:570)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:178)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (8f75448f). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(NIOFSIndexInput(path="E:\workspaces\mylyn-main\ws\.metadata\.mylyn\.taskListIndex\segments_1d")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:501)
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:376)
		... 61 more
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene99' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene912]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:113)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:118)
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:517)
	... 63 more
`

**Comment by ruspl-afed** [comment]
Hello @gnl42 
We need test data to turn this from magic to engineering. Perhaps you have some indexed data in your workspace encoded with `Lucene99`

**Comment by ruspl-afed** [comment]
May be not, but without an example of legacy index it is hardly possible to fix. 
So I agree, let's keep it closed
