### ISSUE TITLE
Test fails to run under windows

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#654]
I'm trying to do a mvn verify build with the current main under windows and I'm seeing this error and I have no idea why it is failing:
```
[INFO] --- tycho-surefire:4.0.9:test (default-test) @ org.eclipse.mylyn.builds.tests ---
[INFO] Executing test runtime with timeout (seconds): 10800, logs, if any, will be placed at: E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\work\data\.metadata\.log
[INFO] Command line:
	[E:\tools\jdk21\bin\java.exe, -Dosgi.noShutdown=false, -Dosgi.os=win32, -Dosgi.ws=win32, -Dosgi.arch=x86_64, -Xmx512m, -Djava.io.tmpdir=E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target, -ea, -Dosgi.clean=true, -jar, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\.m2\repository\p2\osgi\bundle\org.eclipse.equinox.launcher\1.6.900.v20240613-2009\org.eclipse.equinox.launcher-1.6.900.v20240613-2009.jar, -data, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\work\data, -install, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\work, -configuration, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\work\configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\surefire.properties, -testApplication, org.eclipse.ui.ide.workbench, -product, org.eclipse.sdk.ide, -eclipse.keyring, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/.eclipse.keyring, -eclipse.password, E:\workspaces\mylyn-github\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/work/configuration/config.ini, -timeout, 10800000]
Launching application org.eclipse.ui.ide.workbench
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.RuntimeException: Bundle org.eclipse.mylyn.builds.tests is not found
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundle(OsgiSurefireBooter.java:338)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.getBundleClassLoader(OsgiSurefireBooter.java:314)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.createCombinedClassLoader(OsgiSurefireBooter.java:208)

```

**Comment by merks** [comment]
Yes, that fails for me too, even when switched to Tycho 4.0.10

The log file says:
```
!SESSION 2024-12-23 15:49:18.184 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\surefire.properties -testApplication org.eclipse.ui.ide.workbench -product org.eclipse.sdk.ide -eclipse.keyring D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/.eclipse.keyring -eclipse.password D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/work/configuration/config.ini -timeout 10800000
Command-line arguments:  -data D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\work\data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target\surefire.properties -testApplication org.eclipse.ui.ide.workbench -product org.eclipse.sdk.ide -eclipse.keyring D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/.eclipse.keyring -eclipse.password D:\Users\merks\mylyn-main\git\org.eclipse.mylyn\mylyn.builds\org.eclipse.mylyn.builds.tests\target/work/configuration/config.ini -timeout 10800000

!ENTRY org.eclipse.equinox.app 0 0 2024-12-23 15:49:19.713
!MESSAGE Product org.eclipse.sdk.ide could not be found.
```
Have these tests worked on Windows in the past?

**Comment by merks** [comment]
Launched from within the IDE this test does run, so kind of a strange glitch in launching...

**Comment by gnl42** [comment]
I've been using Windows (I should really do something about that) all the time.

Last time I did a build was two months ago
