### ISSUE TITLE
org.eclipse.mylyn.tasks.activity.tests fails

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#70]
mvn clean verify
`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:3.0.3:test (default-test) on project org.eclipse.mylyn.tasks.activity.tests: An unexpected error occurred while launching the test runtime (process returned error code -1 (HRESULT Code 0xFFFFFFFF`

```
!ENTRY org.eclipse.mylyn.tasks.index.core 4 0 2023-03-20 21:27:33.844
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.tasks.index.core [97]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.mylyn.tasks.index.core [osgi.identity; osgi.identity="org.eclipse.mylyn.tasks.index.core"; type="osgi.bundle"; version:Version="3.26.0.N20221223-1911"] because it is exposed to package 'org.apache.lucene.analysis' from resources org.apache.lucene.analyzers-common [osgi.identity; osgi.identity="org.apache.lucene.analyzers-common"; type="osgi.bundle"; version:Version="8.4.1.v20221112-0806"] and org.apache.lucene.core [osgi.identity; osgi.identity="org.apache.lucene.core"; type="osgi.bundle"; version:Version="6.1.0.v20170814-1820"] via two dependency chains.

Chain 1:
  org.eclipse.mylyn.tasks.index.core [osgi.identity; osgi.identity="org.eclipse.mylyn.tasks.index.core"; type="osgi.bundle"; version:Version="3.26.0.N20221223-1911"]
    require: (&(osgi.wiring.bundle=org.apache.lucene.analyzers-common)(bundle-version>=6.1.0))
     |
    provide: osgi.wiring.bundle: org.apache.lucene.analyzers-common
  org.apache.lucene.analyzers-common [osgi.identity; osgi.identity="org.apache.lucene.analyzers-common"; type="osgi.bundle"; version:Version="8.4.1.v20221112-0806"]

Chain 2:
  org.eclipse.mylyn.tasks.index.core [osgi.identity; osgi.identity="org.eclipse.mylyn.tasks.index.core"; type="osgi.bundle"; version:Version="3.26.0.N20221223-1911"]
    require: (&(osgi.wiring.bundle=org.apache.lucene.queryparser)(bundle-version>=6.1.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="6.1.0.v20161115-1612"; osgi.wiring.bundle="org.apache.lucene.queryparser"
  org.apache.lucene.queryparser [osgi.identity; osgi.identity="org.apache.lucene.queryparser"; type="osgi.bundle"; version:Version="6.1.0.v20161115-1612"]
    import: (&(osgi.wiring.package=org.apache.lucene.analysis)(&(version>=6.1.0)(!(version>=6.2.0))))
     |
    export: osgi.wiring.package: org.apache.lucene.analysis
  org.apache.lucene.core [osgi.identity; osgi.identity="org.apache.lucene.core"; type="osgi.bundle"; version:Version="6.1.0.v20170814-1820"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)

!ENTRY org.eclipse.equinox.app 0 0 2023-03-20 21:27:36.056
!MESSAGE Product org.eclipse.sdk.ide could not be found.
```

**Comment by gnl42** [comment]
Might be related.

Created a GitHub Issue instance and pointed to the Mylyn issues.
Complaint about:

`!ENTRY org.eclipse.mylyn.tasks.index.core 4 0 2023-03-21 21:41:35.813
!MESSAGE Failed to update task list index
!STACK 1
org.eclipse.core.runtime.CoreException: Unexpected exception: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="E:\eclipse-mylyn\mylyn-main\Mylyn-Runtime\.metadata\.mylyn\.taskListIndex\segments_1"))): 9 (needs to be between 4 and 6)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.maintainIndex(TaskListIndex.java:1119)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.access$0(TaskListIndex.java:1086)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex$MaintainIndexJob.run(TaskListIndex.java:186)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="E:\eclipse-mylyn\mylyn-main\Mylyn-Runtime\.metadata\.mylyn\.taskListIndex\segments_1"))): 9 (needs to be between 4 and 6)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:297)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:284)
	at org.apache.lucene.index.IndexFileDeleter.<init>(IndexFileDeleter.java:165)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:950)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.createIndexWriter(TaskListIndex.java:1291)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.rebuildIndexCompletely(TaskListIndex.java:1237)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.maintainIndex(TaskListIndex.java:1105)
`

**Comment by gnl42** [comment]
Once the version is forced to 8.4.1, tests fail with "cannot change field "creation_date" from index options=DOCS to inconsistent index options=DOCS_AND_FREQS_AND_POSITIONS"

Appears to be explained by https://lists.archive.carbon60.com/lucene/java-user/439537?page=last
