### ISSUE TITLE
Lucene: Format version is not supported 

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#83]
Seeing this now after #70 merged:

```
org.eclipse.core.runtime.CoreException: Unexpected exception: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="E:\eclipse-workspace-GitHub\.metadata\.mylyn\.taskListIndex\segments_1g"))): 9 (needs to be between 4 and 6)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.maintainIndex(TaskListIndex.java:1119)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.access$0(TaskListIndex.java:1086)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex$MaintainIndexJob.run(TaskListIndex.java:186)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(NIOFSIndexInput(path="E:\eclipse-workspace-GitHub\.metadata\.mylyn\.taskListIndex\segments_1g"))): 9 (needs to be between 4 and 6)
	at org.apache.lucene.codecs.CodecUtil.checkHeaderNoMagic(CodecUtil.java:216)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:297)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:284)
	at org.apache.lucene.index.IndexFileDeleter.<init>(IndexFileDeleter.java:165)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:950)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.createIndexWriter(TaskListIndex.java:1291)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.rebuildIndexCompletely(TaskListIndex.java:1237)
	at org.eclipse.mylyn.internal.tasks.index.core.TaskListIndex.maintainIndex(TaskListIndex.java:1105)
	... 3 more

```

**Comment by gnl42** [comment]
Just create a GitHub Issue connector

**Comment by BeckerFrank** [comment]
I think this is just because you are using a workspace with a previous last run before merging #81.
Can you try if you get this with a workspace with the latest released version and update to the latest milestone.
I hope that in this case you do not get the error.

**Comment by gnl42** [comment]
Just ignore, it was due to leftover lucene files. Once I deleted them from my workspace it clean up the problem
